# Generated by Django 4.1.4 on 2022-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sicoach", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(null=True, upload_to="cover/")),
                ("tanggal", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
