# Generated by Django 4.1.4 on 2022-12-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sicoach", "0002_pembayaran"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pembayaran", old_name="cover", new_name="Bukti",
        ),
    ]
